<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
use SecurePackage\Client\BrowserV8;
use SecurePackage\Security\WebSecurity;
WebSecurity::startSession(); WebSecurity::applyHeaders();
$config=require dirname(__DIR__) . '/config/config.php';
$base=$config['storage']['temp'].DIRECTORY_SEPARATOR.'client-v8'; @mkdir($base,0700,true);
function json_out(array $data,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_SLASHES);exit;}
function body_json():array{$raw=file_get_contents('php://input');$d=json_decode($raw?:'{}',true);return is_array($d)?$d:[];}
function csrf():void{$provided=(string)($_SERVER['HTTP_X_CSRF_TOKEN']??'');if(!hash_equals(WebSecurity::csrfToken(),$provided))json_out(['ok'=>false,'error'=>'Invalid request token.'],403);}
function safe_hex(string $v,int $len):bool{return (bool)preg_match('/^[a-f0-9]{'.$len.'}$/',$v);}
$action=(string)($_GET['action']??'');
if($action==='csrf')json_out(['ok'=>true,'csrf'=>WebSecurity::csrfToken()]);
csrf();
try{
 if($action==='init'){$d=body_json();if((int)($d['chunk_size']??0)!==BrowserV8::CHUNK_SIZE)json_out(['ok'=>false,'error'=>'Unsupported chunk configuration.'],400);$resume=(string)($d['resume_id']??'');if($resume!==''&&safe_hex($resume,48)){$rdir=$base.DIRECTORY_SEPARATOR.hash('sha256',session_id().'|'.$resume);if(is_dir($rdir)&&is_file($rdir.DIRECTORY_SEPARATOR.'owner')&&hash_equals(trim((string)file_get_contents($rdir.DIRECTORY_SEPARATOR.'owner')),hash('sha256',session_id())))json_out(['ok'=>true,'upload_id'=>$resume,'resumed'=>true]);}$id=bin2hex(random_bytes(24));$dir=$base.DIRECTORY_SEPARATOR.hash('sha256',session_id().'|'.$id);mkdir($dir,0700,true);file_put_contents($dir.DIRECTORY_SEPARATOR.'owner',hash('sha256',session_id()),LOCK_EX);file_put_contents($dir.DIRECTORY_SEPARATOR.'state.json',json_encode(['created'=>time(),'chunk_size'=>BrowserV8::CHUNK_SIZE,'chunks'=>[]],JSON_THROW_ON_ERROR),LOCK_EX);json_out(['ok'=>true,'upload_id'=>$id,'resumed'=>false]);}
 $id=(string)($_GET['id']??'');if(!safe_hex($id,48))json_out(['ok'=>false,'error'=>'Invalid upload identifier.'],400);$dir=$base.DIRECTORY_SEPARATOR.hash('sha256',session_id().'|'.$id);if(!is_dir($dir)||!is_file($dir.DIRECTORY_SEPARATOR.'owner'))json_out(['ok'=>false,'error'=>'Upload not found.'],404);if(!hash_equals(trim((string)file_get_contents($dir.DIRECTORY_SEPARATOR.'owner')),hash('sha256',session_id())))json_out(['ok'=>false,'error'=>'Upload not found.'],404);
 if($action==='status'){ $state=json_decode((string)file_get_contents($dir.DIRECTORY_SEPARATOR.'state.json'),true,512,JSON_THROW_ON_ERROR); json_out(['ok'=>true,'chunks'=>array_keys((array)($state['chunks']??[]))]);}
 if($action==='chunk'){$cid=(string)($_SERVER['HTTP_X_CHUNK_ID']??'');$fid=(string)($_SERVER['HTTP_X_FILE_ID']??'');$idx=(string)($_SERVER['HTTP_X_CHUNK_INDEX']??'');if(!safe_hex($cid,64)||!safe_hex($fid,32)||!ctype_digit($idx))json_out(['ok'=>false,'error'=>'Invalid chunk metadata.'],400);$data=file_get_contents('php://input');if($data===false||strlen($data)>BrowserV8::CHUNK_SIZE+64)json_out(['ok'=>false,'error'=>'Invalid chunk body.'],400);$expected=hash('sha256','SECURE-BROWSER-V8|CHUNK|'.$data);if(!hash_equals($cid,$expected))json_out(['ok'=>false,'error'=>'Chunk integrity check failed.'],400);$path=$dir.DIRECTORY_SEPARATOR.'chunks'.DIRECTORY_SEPARATOR.$cid;mkdir(dirname($path),0700,true);if(!is_file($path))file_put_contents($path,$data,LOCK_EX);$state=json_decode((string)file_get_contents($dir.DIRECTORY_SEPARATOR.'state.json'),true,512,JSON_THROW_ON_ERROR);$state['chunks'][$cid]=['file_id'=>$fid,'index'=>(int)$idx,'size'=>strlen($data)];file_put_contents($dir.DIRECTORY_SEPARATOR.'state.json',json_encode($state,JSON_THROW_ON_ERROR),LOCK_EX);json_out(['ok'=>true,'id'=>$cid]);}
 if($action==='finalize'){$d=body_json();$pkg=(string)($d['package_id']??'');if(!BrowserV8::validId($pkg)||$pkg!==$id||!is_string($d['header']??null)||!is_string($d['manifest']??null)||!is_array($d['chunk_ids']??null)||count($d['chunk_ids'])>100000)json_out(['ok'=>false,'error'=>'Invalid finalize request.'],400);$ids=[];foreach($d['chunk_ids'] as $cid){if(!is_string($cid)||!safe_hex($cid,64)||isset($ids[$cid]))json_out(['ok'=>false,'error'=>'Invalid chunk inventory.'],400);$ids[$cid]=true;if(!is_file($dir.DIRECTORY_SEPARATOR.'chunks'.DIRECTORY_SEPARATOR.$cid))json_out(['ok'=>false,'error'=>'Missing encrypted chunk.'],400);}$header=base64_decode($d['header'],true);$manifest=base64_decode($d['manifest'],true);if($header===false||$manifest===false||strlen($header)>1048576||strlen($manifest)>52428800)json_out(['ok'=>false,'error'=>'Invalid encrypted metadata.'],400);$headerData=json_decode($header,true);if(!is_array($headerData)||($headerData['format']??null)!==BrowserV8::FORMAT||(int)($headerData['version']??0)!==BrowserV8::VERSION||($headerData['package_id']??null)!==$pkg||($headerData['chunk_size']??null)!==BrowserV8::CHUNK_SIZE||($headerData['nonce_derivation']??null)!=='HMAC-SHA-256')json_out(['ok'=>false,'error'=>'Invalid encrypted header.'],400);$out=$base.DIRECTORY_SEPARATOR.'packages';mkdir($out,0700,true);$pkgdir=$out.DIRECTORY_SEPARATOR.$pkg;if(is_dir($pkgdir))json_out(['ok'=>false,'error'=>'Package already exists.'],409);mkdir($pkgdir.DIRECTORY_SEPARATOR.'chunks',0700,true);file_put_contents($pkgdir.DIRECTORY_SEPARATOR.'header.bin',$header,LOCK_EX);file_put_contents($pkgdir.DIRECTORY_SEPARATOR.'manifest.bin',$manifest,LOCK_EX);foreach(array_keys($ids) as $cid)rename($dir.DIRECTORY_SEPARATOR.'chunks'.DIRECTORY_SEPARATOR.$cid,$pkgdir.DIRECTORY_SEPARATOR.'chunks'.DIRECTORY_SEPARATOR.$cid);file_put_contents($pkgdir.DIRECTORY_SEPARATOR.'inventory.json',json_encode(['package_id'=>$pkg,'chunk_ids'=>array_keys($ids),'merkle_root'=>(string)($d['merkle_root']??'')],JSON_THROW_ON_ERROR),LOCK_EX);file_put_contents($pkgdir.DIRECTORY_SEPARATOR.'created',date('c'),LOCK_EX);@unlink($dir.DIRECTORY_SEPARATOR.'owner');@unlink($dir.DIRECTORY_SEPARATOR.'state.json');@rmdir($dir.DIRECTORY_SEPARATOR.'chunks');@rmdir($dir);json_out(['ok'=>true,'package_id'=>$pkg]);}
 json_out(['ok'=>false,'error'=>'Unknown action.'],404);
}catch(Throwable){json_out(['ok'=>false,'error'=>'Request failed.'],400);}
